### PR TITLE
add badges

### PR DESCRIPTION
**Pull request by endrjuskr**
Screenshot 2020-05-06 at 11 25 19

* Build is failing because it is on master and we haven't merged it yet
* Last release is not present because we haven't released it yet.

### CODE REVIEW

**Comment by endrjuskr** [comment]
We can add docker hub badge as well

**Comment by TheMP** [comment]
What would show on those badges if PR is merged? Especially the release date - is it taken from github release?
Are we able co confirm that verison above python 3.6 would run?

**Comment by endrjuskr** [comment]
Release is coming from Github

Tests are passing on 3.6 version.

When we merge to develop they will show the same. We need to merge it to master to change values.

**Comment by hrzn** [comment]
Very cool :) 
About downloads / month: maybe not worth showing until we reach some significant numbers?

**Pull request merged**
